### ISSUE TITLE
Room Data base initiate

### ISSUE THREAD

**Issue by ahmed-zedan** [octav8us/KreazTanta#3]
### Code
https://github.com/octav8us/KreazTanta/blob/58d3d728410039216910d4c5d424bbe045cf24a8/app/src/main/java/com/example/kreaz/data/KreazRoomDatabase.kt#L18

### Questions
Why do we use this annotation?

### Code
https://github.com/octav8us/KreazTanta/blob/58d3d728410039216910d4c5d424bbe045cf24a8/app/src/main/java/com/example/kreaz/data/KreazRoomDatabase.kt#L22

### Questions
Why do we use this synchronized?

### Code
https://github.com/octav8us/KreazTanta/blob/58d3d728410039216910d4c5d424bbe045cf24a8/app/src/main/java/com/example/kreaz/data/KreazRoomDatabase.kt#L28

### Questions
Why do we call this method?

#### mentions 

@octav8us

**Comment by octav8us** [comment]
* value of a volatile variable will never be cached, and all writes and reads will be done to and from the main memory. This helps make sure the value of INSTANCE is always up-to-date and the same for all execution threads. It means that changes made by one thread to INSTANCE are visible to all other threads immediately.
* Multiple threads can potentially run into a race condition and ask for a database instance at the same time, resulting in two databases instead of one. Wrapping the code to get the database inside a synchronized block means that only one thread of execution at a time can enter this block of code, which makes sure the database only gets initialized once.
* when database schema changes fallbackToDestructiveMigration() delets the old data and

**Comment by ahmed-zedan** [comment]
Good Answer.
